---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: frontend-1
  image: node
  commands:
  - npm install
  - npm run test
  depends_on:
  - backend
  
---
kind: pipeline
type: docker
name: default-2

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: frontend-1
  image: node
  commands:
  - npm install
  - npm run test
  depends_on:
  - backend
